kafka:
  broker: "kafka:9092"
  topic: "ecolab.beacon.canonical.v1"
  consumer_group_id: "lambda-consumer"

postgres:
  host: "postgres"
  db: "archdb"
  user: "archuser"
  password: "archpass"
  port: 5432

monitoring:
  prometheus_port: 9090

batch:
  interval_seconds: 60

data:
  machine_csv_path: "/config/reference-data/Machines_simulatedV1.csv"

logging:
  level: "INFO"